#!/bin/bash -e

. tests/000-setup

juju scp tests/scripts/test-02-connection ${UNIT_NAME}:/tmp
# This is a trick to avoid the devconf warnings
juju run --unit ${UNIT_NAME} /tmp/test-02-connection &> /dev/null || echo ""
juju run --unit ${UNIT_NAME} /tmp/test-02-connection 2>1 

